# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Q7qspm7Akj5TebEsnS7qi1y6V96EZpV
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, FFMpegWriter
from tqdm import tqdm

# 1. Setup Grid and Parameters
nx, ny = 41, 41
dx = 2 / (nx - 1)
dy = 2 / (ny - 1)
dt = 0.001
viscosity = 0.1
B_field = 1.5  # Magnetic damping
rho = 1.0

# Initialize fields
u = np.zeros((ny, nx))
v = np.zeros((ny, nx))
p = np.zeros((ny, nx))

def update_step(u, v, p):
    un, vn = u.copy(), v.copy()

    # Calculate source term for Pressure Poisson
    b = np.zeros_like(p)
    b[1:-1, 1:-1] = (rho * (1 / dt * ((u[1:-1, 2:] - u[1:-1, 0:-2]) / (2 * dx) + (v[2:, 1:-1] - v[0:-2, 1:-1]) / (2 * dy)) -
                    ((u[1:-1, 2:] - u[1:-1, 0:-2]) / (2 * dx))**2 -
                    2 * ((u[2:, 1:-1] - u[0:-2, 1:-1]) / (2 * dy) * (v[1:-1, 2:] - v[1:-1, 0:-2]) / (2 * dx)) -
                    ((v[2:, 1:-1] - v[0:-2, 1:-1]) / (2 * dy))**2))

    # Pressure Poisson Iterations
    for _ in range(30):
        pn = p.copy()
        p[1:-1, 1:-1] = (((pn[1:-1, 2:] + pn[1:-1, 0:-2]) * dy**2 +
                          (pn[2:, 1:-1] + pn[0:-2, 1:-1]) * dx**2) / (2 * (dx**2 + dy**2)) -
                          dx**2 * dy**2 / (2 * (dx**2 + dy**2)) * b[1:-1, 1:-1])
        p[:, -1] = p[:, -2]; p[0, :] = p[1, :]; p[:, 0] = p[:, 1]; p[-1, :] = 0

    # Velocity updates with Magnetic Term
    u[1:-1, 1:-1] = (un[1:-1, 1:-1] - un[1:-1, 1:-1] * dt / dx * (un[1:-1, 1:-1] - un[1:-1, 0:-2]) -
                     vn[1:-1, 1:-1] * dt / dy * (un[1:-1, 1:-1] - un[0:-2, 1:-1]) -
                     dt / (2 * rho * dx) * (p[1:-1, 2:] - p[1:-1, 0:-2]) +
                     viscosity * dt * ((un[1:-1, 2:] - 2*un[1:-1, 1:-1] + un[1:-1, 0:-2])/dx**2 +
                                       (un[2:, 1:-1] - 2*un[1:-1, 1:-1] + un[0:-2, 1:-1])/dy**2) -
                     B_field**2 * un[1:-1, 1:-1] * dt)

    v[1:-1, 1:-1] = (vn[1:-1, 1:-1] - un[1:-1, 1:-1] * dt / dx * (vn[1:-1, 1:-1] - vn[1:-1, 0:-2]) -
                     vn[1:-1, 1:-1] * dt / dy * (vn[1:-1, 1:-1] - vn[0:-2, 1:-1]) -
                     dt / (2 * rho * dy) * (p[2:, 1:-1] - p[0:-2, 1:-1]) +
                     viscosity * dt * ((vn[1:-1, 2:] - 2*vn[1:-1, 1:-1] + vn[1:-1, 0:-2])/dx**2 +
                                       (vn[2:, 1:-1] - 2*vn[1:-1, 1:-1] + vn[0:-2, 1:-1])/dy**2))

    # Boundaries
    u[-1, :], u[0, :], u[:, 0], u[:, -1] = 1.0, 0, 0, 0
    v[-1, :], v[0, :], v[:, 0], v[:, -1] = 0, 0, 0, 0
    return u, v, p

# 3. Animation Logic
fig, ax = plt.subplots(figsize=(8, 6))
x = np.linspace(0, 2, nx)
y = np.linspace(0, 2, ny)
X, Y = np.meshgrid(x, y)

def animate(i):
    global u, v, p
    ax.clear()
    for _ in range(5): # Skip frames to speed up visual motion
        u, v, p = update_step(u, v, p)

    # Plotting
    cont = ax.contourf(X, Y, np.sqrt(u**2 + v**2), cmap='magma', levels=20)
    ax.streamplot(X, Y, u, v, color='white', linewidth=0.8, density=1.2)
    ax.set_title(f"MHD Fluid Evolution - Step {i*5}")
    return cont,

ani = FuncAnimation(fig, animate, frames=60, interval=50)
ani.save('mhd_simulation.gif', writer='pillow', fps=15)
plt.show()